name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"

# [compatibility_flags]
nodejs_compat = true

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzY3MjUzN2EtNWFmMi00ZmFlLTk1OWQtYzllMjI3NjEzYzYwIiwidGVuYW50X2lkIjoiMzg2ODAwYTU2MWI5ZDg3YzRhYjA2YWVjOWI1YWFjMDA0YzM1ZDMxMTRhODQzNDc4OGY3ZmIwYjkxZjg4MTc2MCIsImludGVybmFsX3NlY3JldCI6IjNjZDFhMTk0LWVkNmQtNDA0My05YTIyLTBlN2Y2MmRjZjhhMCJ9._-ZREojvtA71HGGFdWRVeWh0y-HO6ukwpn_AOs4qcCM"
JWT_SECRET = "secret"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1